{{- if and (not .Values.redis.enabled) .Values.redisConfig.auth.createSecret (not .Values.redisConfig.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openctem.redisPasswordSecretName" . }}
  labels:
    {{- include "openctem.apiLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.redisConfig.auth.passwordKey }}: {{ .Values.redisConfig.auth.password | quote }}
{{- end }}
