{{- if and (not .Values.postgresql.enabled) .Values.database.auth.createSecret (not .Values.database.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openctem.dbCredentialsSecretName" . }}
  labels:
    {{- include "openctem.apiLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.auth.userKey }}: {{ .Values.database.auth.username | quote }}
  {{ .Values.database.auth.passwordKey }}: {{ .Values.database.auth.password | quote }}
{{- end }}
