{{- if and .Values.ui.secret.createSecret (not .Values.ui.secret.existingSecret) }}
{{- $secretName := include "openctem.uiSecretName" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "openctem.uiLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.ui.secret.csrfTokenKey }}: {{ include "openctem.uiSecretCsrfTokenValue" (dict "context" . "existingSecret" $existingSecret) | quote }}
{{- end }}
